In [1]:
import numpy as np
import torch 
import matplotlib.pyplot as plt

print("Numpy :", np.__version__)
print ("PyTorch:", torch.__version__)
print("Cuda Avialiable:", torch.cuda.is_available())
print("Ready to go! 🚄")


Numpy : 2.4.6
PyTorch: 2.12.1+cu130
Cuda Avialiable: True
Ready to go! 🚄


In [2]:
# ============================================
# CS223A Lecture 2 — Spatial Descriptions
# Rotation Matrices & Homogeneous Transforms
# Day 2 — June 20, 2026
# ============================================
import numpy as np 

# -- Basic 3d point ---
#A point P in frame {A}

P = np.array([1,0,0])
print("Point P:", P)


Point P: [1 0 0]


In [3]:
# --- Rotation Matrix ---
# Rotate around Z-axis by angle theta
# This is the most basic rotation in robotics

theta = np.radians(90) 
# Rotation Matrix around z-axis

Rz = np.array([
    [np.cos(theta) , -np.sin(theta) ,0],
    [np.sin(theta) , np.cos(theta) , 0],
    [0 , 0 ,1]
])

print("Rotation matrix (Z, 90):")
P_rotated =Rz @ P # @ is used for matrix multiplication in numpy 
print("\n Original Point P:", P)
print("Rotated Point:", np.round(P_rotated, 3))
print("\nP was on X-axis, after 90° Z rotation it should be on Y-axis")

Rotation matrix (Z, 90):

 Original Point P: [1 0 0]
Rotated Point: [0. 1. 0.]

P was on X-axis, after 90° Z rotation it should be on Y-axis


In [4]:
# --- Homogeneous Transformation Matrix ---
# Combines rotation AND translation into one 4x4 matrix
# This is what ROS2, MoveIt, Isaac all use internally

# Translation vector — move 2 units in X, 3 units in Y
t = np.array([2,3,0])

# Build the 4x4 homogeneous transform
T = np.eye(4)   # start with 4x4 identity matrix
T[:3 , :3] = Rz  # top-left 3x3 = rotation
T[:3,3] = t   # top-right column = translation

print("Homogeneous Transform T:")
print(np.round(T,3))

# Convert P to homogeneous coordinates (add 1 at the end)
P_h = np.array([1,0,0,1])

#Apply full transform
P_transformed = T @ P_h 
print("\nOriginal P (homogeneous):", P_h)
print("Transformed P':", np.round(P_transformed, 3))
print("\nRotated 90° around Z, then translated by [2,3,0]")

Homogeneous Transform T:
[[ 0. -1.  0.  2.]
 [ 1.  0.  0.  3.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

Original P (homogeneous): [1 0 0 1]
Transformed P': [2. 4. 0. 1.]

Rotated 90° around Z, then translated by [2,3,0]


In [6]:
# --- Chaining Transforms ---
# In a robot arm, each joint has its own transform
# Final end-effector position = T1 @ T2 @ T3 @ ... @ point

# Second transform — rotate 45° around Z, translate [1, 0, 0]

theta2 = np.radians(45)
Rz2 = np.array([
    [np.cos(theta2) , -np.sin(theta2), 0 ],
    [np.sin(theta2) , np.cos(theta2), 0],
    [0 , 0, 1]
])

T2 = np.eye(4)
T2[:3, :3] = Rz2
T2[:3, 3] = np.array([1, 0, 0])

print("Transform T1(90 + [2,3,0]):")
print(np.round(T,3))
print("\nTransform T2( 45 + [1,0,0]):")
print(np.round(T2,3))

#Chain them -- T1 then T2
T_combined = T @ T2
print("\nCombined Transform T1 @ T2:")
print(np.round(T_combined, 3))

#Apply to Original point 
P_final = T_combined @ P_h
print("\nPoint after both transforms:", np.round(P_final, 3))

Transform T1(90 + [2,3,0]):
[[ 0. -1.  0.  2.]
 [ 1.  0.  0.  3.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

Transform T2( 45 + [1,0,0]):
[[ 0.707 -0.707  0.     1.   ]
 [ 0.707  0.707  0.     0.   ]
 [ 0.     0.     1.     0.   ]
 [ 0.     0.     0.     1.   ]]

Combined Transform T1 @ T2:
[[-0.707 -0.707  0.     2.   ]
 [ 0.707 -0.707  0.     4.   ]
 [ 0.     0.     1.     0.   ]
 [ 0.     0.     0.     1.   ]]

Point after both transforms: [1.293 4.707 0.    1.   ]
